name: Run contract tests

on: push

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Run web consumer contract tests
        run: npm run test:web:consumer
      - name: Publish contract to Pactflow
        run: npm run publish:pact
      - name: Can I deploy web consumer to test?
        run: npm run can:i:deploy:consumer:test
        if: ${{ github.ref_name != 'main' }}
      - name: Can I deploy web consumer to production?
        run: npm run can:i:deploy:consumer:production
        if: ${{ github.ref_name == 'main' }}
      - name: Record web consumer deployment
        run: npm run record:web:consumer:deployment
        if: ${{ github.ref_name == 'main' }}